<a href="https://colab.research.google.com/github/Jakemeister7/Data-Analysis-With-Python-Course/blob/main/Numpy_7_Sorting_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Sort Numerically
np1 = np.array([6, 7, 4, 9, 0, 2, 1])
np.sort(np1)
print(np1)
print(np.sort(np1))

[6 7 4 9 0 2 1]
[0 1 2 4 6 7 9]


In [6]:
# Reverse?
np9 = np.sort(np1)
print(np9) # ascending low to high
# Reverse it to descending high to low
np9 = np9[::-1]
print(np9)

[0 1 2 4 6 7 9]
[9 7 6 4 2 1 0]


In [9]:
# Sort Alphabetically
np2 = np.array(['Jo', 'Bob', 'Rob', 'Jake', 'Sally'])
print(np2)
# Sort low to high
print(np.sort(np2))

['Jo' 'Bob' 'Rob' 'Jake' 'Sally']
['Bob' 'Jake' 'Jo' 'Rob' 'Sally']


In [10]:
# Sort Booleans T(1)/F(0)
np3 = np.array([True, False, False, True])
print(np3)
print(np.sort(np3))

[ True False False  True]
[False False  True  True]


In [11]:
# Sort on 2-D Arrays; sorts in each row
np4 = np.array([[6, 7, 1, 9], [8, 3, 5, 0]])
print(np.sort(np4))

[[1 6 7 9]
 [0 3 5 8]]
