<a href="https://colab.research.google.com/github/Jakemeister7/Data-Analysis-With-Python-Course/blob/main/Numpy_1_Python_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Python list
my_list = [1,2,3,4,5, 'John', True]
my_list2 = [6,7,8, my_list]

In [ ]:
# Import Numpy
import numpy as np

In [ ]:
# Create a numpy array
import numpy as np
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np1[2])

[0 1 2 3 4 5 6 7 8 9]
2


In [ ]:
# Shape - shows the number of elements in the array like the python len function
print(np1.shape)

(10,)


In [ ]:
# Arange
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Step
np3 = np.arange(0,12,2)
print(np3)

[ 0  2  4  6  8 10]


In [ ]:
# Zeros
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Multi-Dimensional Array with Zeros
np5 = np.zeros((5,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# Full
np6 = np.full((10), 'Bob')
print(np6)

['Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob']


In [ ]:
# Multi-Dimensional Array with Full
np7 = np.full((2,10), 'Bob')
print(np7)

[['Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob']
 ['Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob']]


In [ ]:
# Convert Python List to Numpy Array
# my_list
my_list = [0,1,2,3,4,5]
np8 = np.array(my_list)
print(np8)
print(my_list)

[0 1 2 3 4 5]
[0, 1, 2, 3, 4, 5]
