<a href="https://colab.research.google.com/github/Jakemeister7/Data-Analysis-With-Python-Course/blob/main/Numpy_5_Shape_and_Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# Create 1-D Array and Get Shape
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1.shape)

(12,)


In [ ]:
# Create 2-D Array and Get Shape (returns rows/column-elements)
np2 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(np2.shape)
print(np2)

(2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
# Reshape 1-D Array into a 2-D Array
np3 =np1.reshape(3,4)
print(np3)
print(np3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
# Reshape 1-D array into a 3-D Array
np4 = np1.reshape(2,3,2)
print(np4)
print(np4.shape)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [ ]:
# Flatten 3-d to 1-D
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [ ]:
# Flatten 3-d to 2-D
np6 = np4.reshape(-1,2)
print(np6)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
