<a href="https://colab.research.google.com/github/Jakemeister7/Data-Analysis-With-Python-Course/blob/main/Numpy_8_Searching.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
# Searching returns index number
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x = np.where(np1 == 3)
print(x[0])
print(np1[x])

[2]
[3]


In [6]:
# More than 1 Item
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 3])
x = np.where(np1 == 3)
print(x)

(array([ 2, 10]),)


In [7]:
# Print them out
print(np1[x])

[3 3]


In [9]:
# Return Even Items
y = np.where(np1 % 2 == 0)
print(y)
print(np1[y])

(array([1, 3, 5, 7, 9]),)
[ 2  4  6  8 10]


In [10]:
# Return Odd Items
y = np.where(np1 % 2 == 1)
print(y)
print(np1[y])


(array([ 0,  2,  4,  6,  8, 10]),)
[1 3 5 7 9 3]


In [12]:
# Greater than
y = np.where(np1 >5)
print(y)
print(np1[y])

(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]
