<a href="https://colab.research.google.com/github/Jakemeister7/Data-Analysis-With-Python-Course/blob/main/Pandas_2_Manual_DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas - Manual DataFrames

In [3]:
# Import Pandas
import pandas as pd
import numpy as np
from numpy.random import rand

In [7]:
# Create a Random Data
my_data = rand(4,3) # rows/columns
print(my_data)

[[0.21061202 0.65360649 0.05041513]
 [0.14434467 0.90318791 0.23539791]
 [0.83590678 0.47681092 0.45770382]
 [0.39051275 0.8142145  0.94708708]]


In [9]:
# Create headers
my_rows = ['A', 'B', 'C', 'D']
my_cols = ['Monday', 'Tuesday', 'Friday']

In [11]:
# Create our DataFrame!!
my_df = pd.DataFrame(my_data, my_rows, my_cols)

In [12]:
# print
print(my_df)

     Monday   Tuesday    Friday
A  0.210612  0.653606  0.050415
B  0.144345  0.903188  0.235398
C  0.835907  0.476811  0.457704
D  0.390513  0.814214  0.947087


In [14]:
# print with formatting
my_df

Monday   Tuesday    Friday
A  0.210612  0.653606  0.050415
B  0.144345  0.903188  0.235398
C  0.835907  0.476811  0.457704
D  0.390513  0.814214  0.947087